# fohuw theme
# module: configuration
#     derived from docsy.dev
#     all commented out for now...

# hugoVersion:
#   extended: true
#   min: 0.73.0
# mounts:
#   - source: assets
#     target: assets
#   - source: node_modules/bootstrap
#     target: assets/vendor/bootstrap
#   - source: node_modules/@fortawesome/fontawesome-free
#     target: assets/vendor/Font-Awesome
#   - source: i18n
#     target: i18n
#   - source: layouts
#     target: layouts
#   - source: static
#     target: static
#   - source: node_modules/@fortawesome/fontawesome-free/webfonts
#     target: static/webfonts
#   # Mounts for projects using Docsy as an NPM package. The source path prefix
#   # "../.." moves out of themes/docsy so that Docsy can find its dependencies.
#   - source: ../../node_modules/bootstrap
#     target: assets/vendor/bootstrap
#   - source: ../../node_modules/@fortawesome/fontawesome-free
#     target: assets/vendor/Font-Awesome
#   - source: ../../node_modules/@fortawesome/fontawesome-free/webfonts
#     target: static/webfonts
