# fohuw theme
# params: configuration
#     these are the params used to build the documentation site

time_format_blog: Monday, 02 Jan 2006
time_format_default: "2006-01-02"
rss_sections: [blog]
drawio:
  enable: true
