# fohuw theme
# This file contains all the sites.Params.xxx properties
# These values here are used to build the documentation site.
# Change them to your favourite values for your website
baseURL: /
time_format_blog: Monday, 02 Jan 2006
time_format_default: "2006-01-02"
rss_sections: [blog]
# the releases file is in assets/data/releases.yaml
releaseTracking: data/releases.yaml

#                 _                                       _
#   __ _   _  _  | |_   ___   ___   _ _    _  _   _ __   | |__   ___   _ _
#  / _` | | || | |  _| / _ \ |___| | ' \  | || | | '  \  | '_ \ / -_) | '_|
#  \__,_|  \_,_|  \__| \___/       |_||_|  \_,_| |_|_|_| |_.__/ \___| |_|
# fohuw can number headings : ## {{% H 2 %}} Level-2-Heading 
# These are the default settings that can be overridden per-page in frontmatter
heading:
  prefix: ""
  separator: "."
  suffix: ""
#          _   _     _             _
#   __ _  (_) | |_  | |_    _  _  | |__
#  / _` | | | |  _| | ' \  | || | | '_ \
#  \__, | |_|  \__| |_||_|  \_,_| |_.__/
#  |___/
# github information for providing "edit page" or "issues"
github:
  # Account URL for in-page links to opening issues and suggesting changes
  url: https://github.com/mrmxf
  # Repository name for in-page links to opening issues and suggesting changes
  repo: fohuw
  # what branch should the generated site point to e.g. main
  branch: main
  # path to the content folder relative to project root e.g. sample/fohuw-docs/
  contentParent: documentation
  # If one of your languages is in "/content" (not /content/de) mark it here
  # this is a workaround because a partial cannot read site.DefaultContentLanguageinSubdir
  languageInContentFolder: en

# Specify a value here if your content directory is not in your repo's root directory

#          _
#   _  _  (_)
#  | || | | |
#   \_,_| |_|
ui:
  # look for logo.svg or logo.png or logo.jpg, set baseURL for this to work right
  logo: /brand/logo
  # some elements of the ui can be hidden
  hide:
    navbar:
      logo: false
      title: false
  footer:
    showSiteTitle: true
    showSiteVersion: true
    links:
      - label: Built with
        title: FoHuW
        url: https://github.com/mrmxf/fohuw
      - label: by
        title: Mr MXF
        url: https://mrmxf.com
      - label: copyright ©
        title: Mr MXF
        link: https://mrmxf.com
      - title: Privacy Policy
        link: https://termly.io/resources/templates/privacy-policy-template/
      - title: Contact
        link: /contact
      - title: About
        link: /about

#           _                         _
#   __   __| |  _ _      _  _   _ _  | |  ___
#  / _| / _` | | ' \    | || | | '_| | | (_-<
#  \__| \__,_| |_||_|    \_,_| |_|   |_| /__/
# certain resources will be pulled from cdn in partials/tmpl/head-cdn.html
# each url is {{prefix}}{{version}}{{suffix}} with no extra processing
# .integrity is optional
cdn:
  - name: jQuery
    version: 3.7.1
    prefix: https://cdn.jsdelivr.net/npm/jquery@
    suffix: /dist/jquery.min.js
    integrity: sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=
  - name: fomantic-ui css
    version: 2.9.4
    prefix: https://cdn.jsdelivr.net/npm/fomantic-ui@
    suffix: /dist/semantic.min.css
    integrity: sha256-xlp3XbXCVlcKYMpXDnziC1QzN9j0SQiDjRiZ0qu6IOc=
  - name: fomantic-ui js
    version: 2.9.4
    prefix: https://cdn.jsdelivr.net/npm/fomantic-ui@
    suffix: /dist/semantic.min.js
    integrity: sha256-Zh6NZwjzefLXtkIYJygkBuwIxUhZjOPgxKHvlGPo688=
  - name: mermaid
    version: 11.6.0
    prefix: https://cdn.jsdelivr.net/npm/mermaid@
    suffix: /dist/mermaid.min.js
    integrity: sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=

