version: "0.1"

services:

   site:
      image: mrmxf/fohuw
      build:
         context: .
      ports:
         - "1313:1313"
      user: "${USER}"
      volumes:
         - /app/fohuw/fohuwguide/node_modules
         - .:/app/fohuw
