name = "FoHuW"
license = "BSD 3-clause"
licenselink = "https://github.com/mrmxf/fohuw/blob/main/LICENSE"
description = "A Hugo theme based on Docsy and Fomantic-ui"
homepage = "https://mrmxf.com"
tags = ["documentation", "multilingual", "customizable", "responsive", "docs"]
features = []
min_version = 0.144

[author]
  name = "Mr MXF"
  homepage = "https://mrmxf.com"
