name = "FoHuW"
license = "Apache 2.0"
licenselink = "https://github.com/mrmxf/fohuw/blob/main/LICENSE"
description = "A Hugo theme for creative & technical documentation sites"
homepage = "https://mrmxf.com"
tags = ["documentation", "multilingual", "customizable", "responsive", "docs"]
features = []
min_version = 0.120

[author]
  name = "Mr MXF"
  homepage = "https://mrmxf.com"
